import { ColorToken, GeometrySpec, TypographySpec } from "@/types/tokens";

/**
 * Generates Tailwind CSS v4 `@theme` configuration block.
 */
export function generateTailwindV4Theme(params: {
  colors: ColorToken[];
  typography: TypographySpec;
  geometry: GeometrySpec;
}): string {
  const { colors, typography, geometry } = params;

  const colorProperties = colors
    .map((c) => `  --color-${c.name.replace(/^bg-|^text-/, "")}: ${c.hex};`)
    .join("\n");

  const spacingProperties = geometry.spacingRampPx
    .slice(1, 8)
    .map((s, idx) => `  --spacing-${idx + 1}: ${(s / 16).toFixed(3)}rem; /* ${s}px */`)
    .join("\n");

  return `/* Generated by Deslop // Tailwind CSS v4 Theme */
@theme {
  /* Colors */
${colorProperties}

  /* Typography */
  --font-sans: "${typography.bodyFamily}", system-ui, sans-serif;
  --font-display: "${typography.displayFamily}", system-ui, sans-serif;
  --font-mono: "${typography.monoFamily}", monospace;

  /* Spacing Grid (8pt baseline) */
${spacingProperties}

  /* Border Radii */
  --radius-sm: ${geometry.radii.controlPx}px;
  --radius-md: ${geometry.radii.cardPx}px;
  --radius-full: 9999px;
}
`;
}
